// List of musical genres for studios and services
// These will be used for filtering and categorization
export const genres = [
  'Rock',
  'Pop',
  'Jazz',
  'Hip-Hop',
  'Electronic',
  'Classical',
  'Country',
  'R&B',
  'Reggae',
  'Metal',
  'Folk',
  'Blues',
  'Latin',
  'World Music',
  'Gospel',
  'Punk',
  'Alternative',
  'Indie',
  'Soul',
  'Funk',
  'Disco',
  'House',
  'Techno',
  'EDM',
  'Ambient',
  'Acoustic',
  'Singer-Songwriter',
  'Rap',
  'Trap',
  'Instrumental',
  'Orchestral',
  'Film Score',
  'Podcast',
  'Voice Acting',
  'Commercial'
];
