// List of musical genres for studios and services
// These will be used for filtering and categorization
export const genres = [
  'Rock',
  'Pop',
  'Jazz',
  'Hip-Hop',
  'Electronic',
  'Classical',
  'Country',
  'R&B',
  'Reggae',
  'Metal',
  'Folk',
  'Blues',
  'Latin',
  'World Music',
  'Gospel',
  'Punk',
  'Alternative',
  'Indie',
  'Soul',
  'Funk',
  'Disco',
  'House',
  'Techno',
  'Drum & Bass',
  'Dubstep',
  'Ambient',
  'Experimental',
  'Acoustic',
  'Singer-Songwriter',
  'Rap',
  'Trap',
  'EDM',
  'Trance',
  'Hardcore',
  'Progressive Rock',
  'Psychedelic',
  'Ska',
  'Grunge',
  'New Wave',
  'Synth-pop',
  'Post-rock',
  'Shoegaze',
  'Noise',
  'Industrial',
  'Goth',
  'Emo',
  'Pop-punk',
  'Hard Rock',
  'Soft Rock',
  'Ballad',
  'Instrumental',
  'Orchestral',
  'Chamber Music',
  'Opera',
  'Musical Theater',
  'Film Score',
  'Video Game Music',
  'Podcast',
  'Audiobook',
  'Voice Acting',
  'Commercial',
  'Jingle'
];
