import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import fs from 'fs';
// Sitemap is generated by custom script (scripts/generate-sitemap.js) after build
// which includes dynamic studio pages from the API
// Pre-rendering is handled by scripts/prerender.js after build

export default defineConfig(({ _command, mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  return {
    plugins: [
      {
        name: 'html-transform',
        transformIndexHtml(html) {
          let transformedHtml = html;

          // Replace Google Maps API placeholder
          transformedHtml = transformedHtml.replace(
            '<!-- GOOGLE_MAPS_API -->',
            `<script 
              src="https://maps.googleapis.com/maps/api/js?key=${env.VITE_GOOGLE_MAPS_API_KEY}&loading=async&libraries=places" 
              defer>
            </script>`
          );

          return transformedHtml;
        }
      },
      {
        name: 'copy-logo',
        buildStart() {
          // Copy logo file for SEO schema (build time)
          const logoSource = path.resolve(__dirname, 'public/android-chrome-512x512.png');
          const logoDest = path.resolve(__dirname, 'public/logo.png');
          if (fs.existsSync(logoSource) && !fs.existsSync(logoDest)) {
            fs.copyFileSync(logoSource, logoDest);
          }
        },
        configureServer(server) {
          // Ensure logo exists in dev mode
          server.httpServer?.once('listening', () => {
            const logoSource = path.resolve(__dirname, 'public/android-chrome-512x512.png');
            const logoDest = path.resolve(__dirname, 'public/logo.png');
            if (fs.existsSync(logoSource) && !fs.existsSync(logoDest)) {
              fs.copyFileSync(logoSource, logoDest);
            }
          });
        }
      },
      react()
      // Sitemap plugin removed - using custom script instead (scripts/generate-sitemap.js)
      // which includes dynamic studio pages from API
    ],
    build: {
      outDir: 'dist',
      rollupOptions: {
        output: {
          manualChunks: {
            // Vendor chunks
            'react-vendor': ['react', 'react-dom', 'react-router-dom'],
            'ui-vendor': ['@mui/material', '@mui/icons-material', '@mui/x-date-pickers'],
            // Note: mapbox removed from manual chunks - let Vite naturally code-split with lazy components
            'query-vendor': ['@tanstack/react-query', '@tanstack/react-query-persist-client'],
            'i18n-vendor': ['i18next', 'react-i18next', 'i18next-browser-languagedetector'],
            'animation-vendor': ['react-spring', '@use-gesture/react'],
            'calendar-vendor': [
              '@fullcalendar/core',
              '@fullcalendar/react',
              '@fullcalendar/daygrid',
              '@fullcalendar/timegrid',
              '@fullcalendar/interaction',
              '@fullcalendar/list'
            ]
          }
        }
      },
      chunkSizeWarningLimit: 1000
    },
    resolve: {
      alias: {
        '@shared': path.resolve(__dirname, './src/shared'),
        '@features': path.resolve(__dirname, './src/features'),
        '@app': path.resolve(__dirname, './src/app'),
        '@core': path.resolve(__dirname, './src/core'),
        '@types': path.resolve(__dirname, './src/types')
      }
    },
    css: {
      preprocessorOptions: {
        scss: {
          includePaths: [
            path.resolve(__dirname, './src/assets/styles'),
            path.resolve(__dirname, './src/shared/components/forms/styles')
          ]
        }
      }
    }
  };
});
