export const videoAndPhotographySubCategories = [
  'Film Production',
  'Photography Studio',
  'Video Editing',
  'Cinematography',
  'Commercial Photography',
  'Documentary Production',
  'Wedding Photography',
  'Portrait Photography',
  'Fashion Photography',
  'Event Videography',
  'Music Video Production',
  'Drone Photography/Videography',
  'Green Screen Studio',
  'Food Photography',
  'Product Photography',
  'Studio Rental',
  'Video Animation',
  'Virtual Tour Creation',
  '360° Photography/Videography',
  'Headshot Photography',
  'Real Estate Photography/Videography',
  'Corporate Videography',
  'Artistic Photography',
  'Educational Videos',
  'Travel Photography/Videography',
  'Video Game Streaming Setup',
  'Video Blogging',
  'Stock Photography/Videography',
  'Visual Effects',
  'Stop Motion Animation'
];
