export const musicSubCategories = [
  'Music Production',
  'Podcast Recording',
  'Audio Engineering',
  'Film Sound',
  'Voiceover',
  'Recording',
  'Mastering',
  'Mixing',
  'Remote Collaboration',
  'Virtual Reality',
  'Live Streaming',
  'Foley',
  'Sound Design',
  'Field Recording',
  'Post Production',
  'Audio Restoration',
  'Educational',
  'Commercial',
  'Personal Studio'
];
