import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useCreateAddOnMutation } from '@shared/hooks';
import { AddOn } from 'src/types/index';
import { toast } from 'sonner';
import { AddIcon, CloseIcon, DeleteIcon } from '@shared/components/icons';
import './styles/_create-addon-form.scss';

// Type for pending add-ons (without _id, which will be generated by backend)
export type PendingAddOn = Omit<AddOn, '_id'> & { _id?: string };

interface CreateAddOnFormProps {
  mode?: 'local' | 'immediate';
  onAdd?: (addOn: PendingAddOn) => void;
  onRemove?: (index: number) => void;
  onUpdate?: (index: number, addOn: PendingAddOn) => void;
  pendingAddOns?: PendingAddOn[];
}

export const CreateAddOnForm = ({
  mode = 'immediate',
  onAdd,
  onRemove,
  onUpdate,
  pendingAddOns = []
}: CreateAddOnFormProps = {}) => {
  const { itemId } = useParams();
  const { t } = useTranslation('forms');
  const createAddOnMutation = useCreateAddOnMutation(itemId ? itemId : undefined);
  const [isFormVisible, setIsFormVisible] = useState<boolean>(false);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);

  // Form state
  const [formData, setFormData] = useState({
    nameEn: '',
    nameHe: '',
    descriptionEn: '',
    descriptionHe: '',
    price: '',
    priceUnit: 'flat' as 'flat' | 'hourly' | 'daily',
    isActive: true
  });

  const resetForm = () => {
    setFormData({
      nameEn: '',
      nameHe: '',
      descriptionEn: '',
      descriptionHe: '',
      price: '',
      priceUnit: 'flat',
      isActive: true
    });
  };

  const getPricePerLabel = (value: string) => {
    const labels: Record<string, string> = {
      flat: 'Flat Fee',
      hourly: 'Per Hour',
      daily: 'Per Day',
      hour: 'Per Hour',
      day: 'Per Day'
    };
    return labels[value] || value;
  };

  const handleSubmit = () => {
    if (!formData.nameEn || !formData.price) {
      toast.error(t('form.addOn.errors.requiredFields'));
      return;
    }

    const existingAddOn = editingIndex !== null ? pendingAddOns[editingIndex] : null;

    const addOnData: PendingAddOn = {
      name: {
        en: formData.nameEn,
        he: formData.nameHe || ''
      },
      description: {
        en: formData.descriptionEn || '',
        he: formData.descriptionHe || ''
      },
      price: Number(formData.price),
      pricePer: formData.priceUnit === 'hourly' ? 'hour' : formData.priceUnit === 'daily' ? 'day' : 'flat',
      itemId: itemId,
      isActive: formData.isActive,
      _id: existingAddOn?._id
    };

    if (editingIndex !== null && onUpdate) {
      onUpdate(editingIndex, addOnData);
      setEditingIndex(null);
      resetForm();
      setIsFormVisible(false);
      return;
    }

    if (mode === 'local' && onAdd) {
      onAdd(addOnData);
      resetForm();
      setIsFormVisible(false);
      toast.success(t('form.addOn.addedToList'));
    } else {
      if (!itemId) {
        toast.error(t('form.addOn.errors.itemIdRequired'));
        return;
      }
      const addOnForBackend: AddOn = {
        ...addOnData,
        _id: ''
      };
      createAddOnMutation.mutate(addOnForBackend, {
        onSuccess: () => {
          resetForm();
          setIsFormVisible(false);
        }
      });
    }
  };

  const handleClose = () => {
    setEditingIndex(null);
    resetForm();
    setIsFormVisible(false);
  };

  const visibleAddOnsCount = Math.max(0, editingIndex !== null ? pendingAddOns.length - 1 : pendingAddOns.length);
  const canSubmit = formData.nameEn && formData.price;

  return (
    <section className="create-addon-form-container">
      {/* Add-ons List */}
      {mode === 'local' && visibleAddOnsCount > 0 && (
        <div className="pending-addons-list">
          <h3>
            {t('form.addOn.pending')} ({visibleAddOnsCount})
          </h3>
          <div>
            {pendingAddOns.map((addOn, index) =>
              editingIndex === index ? null : (
                <div key={addOn._id || index} className={`pending-addon-card ${!addOn.isActive ? 'inactive' : ''}`}>
                  <div className="pending-addon-content">
                    <div className="pending-addon-name-row">
                      <span className="pending-addon-title">{addOn.name?.en || t('form.addOn.untitled')}</span>
                      {addOn.name?.he && <span className="pending-addon-title-he">({addOn.name.he})</span>}
                      {!addOn.isActive && (
                        <span className="pending-addon-badge">
                          {t('form.addOn.inactive', { defaultValue: 'Inactive' })}
                        </span>
                      )}
                    </div>
                    {addOn.description?.en && <div className="pending-addon-description">{addOn.description.en}</div>}
                    <div className="pending-addon-type">{getPricePerLabel(addOn.pricePer || 'flat')}</div>
                  </div>
                  <div className="pending-addon-actions">
                    {addOn.price !== undefined && <div className="pending-addon-price">₪{addOn.price}</div>}
                    {onRemove && (
                      <button
                        type="button"
                        className="pending-addon-delete"
                        onClick={() => onRemove(index)}
                        title={t('form.addOn.remove')}
                        aria-label={t('form.addOn.remove')}
                      >
                        <DeleteIcon />
                      </button>
                    )}
                  </div>
                </div>
              )
            )}
          </div>
        </div>
      )}

      {/* Add New Form or Button */}
      {isFormVisible ? (
        <div className="addon-form-content">
          {/* Header */}
          <div className="addon-form-header">
            <h3 className="addon-form-title">
              {editingIndex !== null
                ? t('form.addOn.editTitle')
                : t('form.addOn.newAddOn', { defaultValue: 'New Add-on' })}
            </h3>
            <button type="button" className="addon-form-close" onClick={handleClose} aria-label={t('form.addOn.close')}>
              <CloseIcon />
            </button>
          </div>

          {/* Fields */}
          <div className="addon-form-fields">
            {/* Name (English) */}
            <div className="addon-form-field">
              <label className="addon-form-label">
                {t('form.addOn.fields.nameEn', { defaultValue: 'Name (English)' })}
              </label>
              <input
                type="text"
                autoFocus
                value={formData.nameEn}
                onChange={(e) => setFormData({ ...formData, nameEn: e.target.value })}
                placeholder={t('form.addOn.placeholders.nameEn', { defaultValue: 'e.g. Drum Kit Rental' })}
                className="addon-form-input"
              />
            </div>

            {/* Name (Hebrew) */}
            <div className="addon-form-field">
              <label className="addon-form-label">
                {t('form.addOn.fields.nameHe', { defaultValue: 'Name (Hebrew)' })}
              </label>
              <input
                type="text"
                dir="rtl"
                value={formData.nameHe}
                onChange={(e) => setFormData({ ...formData, nameHe: e.target.value })}
                placeholder={t('form.addOn.placeholders.nameHe', { defaultValue: 'לדוגמה: השכרת מערכת תופים' })}
                className="addon-form-input"
              />
            </div>

            {/* Description (English) */}
            <div className="addon-form-field">
              <label className="addon-form-label">
                {t('form.addOn.fields.descriptionEn', { defaultValue: 'Description (English)' })}
              </label>
              <textarea
                value={formData.descriptionEn}
                onChange={(e) => setFormData({ ...formData, descriptionEn: e.target.value })}
                placeholder={t('form.addOn.placeholders.descriptionEn', {
                  defaultValue: "Describe what's included..."
                })}
                className="addon-form-textarea"
                rows={2}
              />
            </div>

            {/* Description (Hebrew) */}
            <div className="addon-form-field">
              <label className="addon-form-label">
                {t('form.addOn.fields.descriptionHe', { defaultValue: 'Description (Hebrew)' })}
              </label>
              <textarea
                dir="rtl"
                value={formData.descriptionHe}
                onChange={(e) => setFormData({ ...formData, descriptionHe: e.target.value })}
                placeholder={t('form.addOn.placeholders.descriptionHe', { defaultValue: 'תאר מה כלול...' })}
                className="addon-form-textarea"
                rows={2}
              />
            </div>

            {/* Price and Unit Grid */}
            <div className="addon-form-grid">
              <div className="addon-form-field">
                <label className="addon-form-label">
                  {t('form.addOn.fields.price', { defaultValue: 'Price (₪)' })}
                </label>
                <input
                  type="number"
                  value={formData.price}
                  onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                  placeholder="0"
                  className="addon-form-input"
                />
              </div>

              <div className="addon-form-field">
                <label className="addon-form-label">
                  {t('form.addOn.fields.priceUnit', { defaultValue: 'Price Unit' })}
                </label>
                <div className="addon-form-select-wrapper">
                  <select
                    value={formData.priceUnit}
                    onChange={(e) =>
                      setFormData({ ...formData, priceUnit: e.target.value as 'flat' | 'hourly' | 'daily' })
                    }
                    className="addon-form-select"
                  >
                    <option value="flat">{t('form.addOn.pricePer.flatOption', { defaultValue: 'Flat Fee' })}</option>
                    <option value="hourly">{t('form.addOn.pricePer.hourOption', { defaultValue: 'Per Hour' })}</option>
                    <option value="daily">{t('form.addOn.pricePer.dayOption', { defaultValue: 'Per Day' })}</option>
                  </select>
                  <div className="addon-form-select-arrow">
                    <svg width="10" height="6" viewBox="0 0 10 6" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path
                        d="M1 1L5 5L9 1"
                        stroke="currentColor"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </div>
                </div>
              </div>
            </div>

            {/* Active Checkbox */}
            <div className="addon-form-checkbox-row">
              <button
                type="button"
                onClick={() => setFormData({ ...formData, isActive: !formData.isActive })}
                className={`addon-form-checkbox ${formData.isActive ? 'checked' : ''}`}
                aria-checked={formData.isActive}
                role="checkbox"
              />
              <span className="addon-form-checkbox-label">
                {t('form.addOn.fields.activeStatus', { defaultValue: 'Active Status' })}
              </span>
            </div>
          </div>

          {/* Footer */}
          <div className="addon-form-footer">
            <button type="button" onClick={handleSubmit} disabled={!canSubmit} className="addon-form-submit">
              {editingIndex !== null
                ? t('form.submit.editAddOn', { defaultValue: 'Update Add-On' })
                : t('form.addOn.addItem')}
            </button>
          </div>
        </div>
      ) : (
        <button
          type="button"
          className="add-addon-button"
          onClick={() => setIsFormVisible(true)}
          title={t('form.addOn.createNew')}
          aria-label={t('form.addOn.createNew')}
        >
          <AddIcon className="add-addon-icon" />
          <span className="add-addon-text">{t('form.addOn.createNew')}</span>
        </button>
      )}
    </section>
  );
};
